project:
  type: website
  pre-render: pre_render_script.R

bibliography: 
  - book.bib
  - packages.bib
biblio-style: apalike
link-citations: yes
links-as-notes: true

execute: 
  eval: true
  echo: true
  warning: true
  message: false
  cache: false
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/www\.tidy-finance\.org\/custom
    citations-hover: true
    footnotes-hover: true
    code-link: false
    fig-align: "center"
    fig-width: 7
    fig-height: 5
    fig-dpi: 300

website:
  title: "Tidy Finance"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Book
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    background: "#3b9ab2"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 0
    pinned: true
    contents:
      - section: "Tidy Finance with R"
        contents:
          - index.qmd
      - section: "Getting Started"
        contents:
          - introduction-to-tidy-finance.qmd
      - section: "Appendix"
        contents: 
          - cover-design.qmd

editor: source
