project:
  type: website

website:
  title: "Tidy Finance"
  navbar:
    left:
      - href: index.qmd
        text: Book
      - href: blog.qmd
        text: Blog
      - about.qmd
    background: "#3b9ab2"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Intro"
        contents:
          - intro.qmd
      - section: "Content"
        contents:
          - summary.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

