project:
  type: website
  output-dir: docs
  pre-render: r/pre_render_script.R

bibliography: 
  - bib/book.bib
  - bib/packages.bib
biblio-style: apalike
link-citations: true
links-as-notes: true

execute: 
  freeze: auto
  eval: true
  echo: true
  warning: true
  message: false
  cache: false
  
format:
  html:
    theme: 
      light: [cosmo, styling/theme-light.scss]
    css: styling/styles.css
    toc: true
    section-divs: true
    number-sections: false
    embed-resources: false
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.tidy-finance\.org'
    citations-hover: true
    footnotes-hover: true
    code-link: false
    fig-align: "center"
    fig-width: 7
    fig-height: 5
    fig-dpi: 300

website:
  title: "Tidy Finance"
  site-url: https://www.tidy-finance.org
  repo-url: https://github.com/tidy-finance/website
  repo-actions: [edit, issue]
  description: "An opinionated approach on empirical research in financial economics"
  favicon: images/favicon.png
  open-graph: true
  page-navigation: true
  google-analytics: 
    tracking-id: "G-DH3KZSMJ5W"
    anonymze-ip: true
  cookie-consent: 
    type: express
    style: interstitial 
    palette: light
  navbar:
    logo: images/logo-website-white.png
    pinned: false
    left:
      - href: r/index.qmd
        text: R
      - href: python/index.qmd
        text: Python
      - href: blog.qmd
        text: Blog
      - href: contribute.qmd
        text: Contribute
      - href: support.qmd
        text: Support
    right:
      - icon: rss
        href: blog.xml
  sidebar:
    - id: tidy-finance-with-r
      style: "floating"
      search: true
      collapse-level: 0
      pinned: true
      contents:
        - section: "Tidy Finance with R"
          contents:
            - r/index.qmd
        - section: "Getting Started"
          contents:
            - r/introduction-to-tidy-finance.qmd
        - section: "Financial Data"
          contents:
            - r/accessing-and-managing-financial-data.qmd
            - r/wrds-crsp-and-compustat.qmd
            - r/trace-and-fisd.qmd
            - r/other-data-providers.qmd
        - section: "Asset Pricing"
          contents: 
            - r/beta-estimation.qmd
            - r/univariate-portfolio-sorts.qmd
            - r/size-sorts-and-p-hacking.qmd
            - r/value-and-bivariate-sorts.qmd
            - r/replicating-fama-and-french-factors.qmd
            - r/fama-macbeth-regressions.qmd
        - section: "Modeling and Machine Learning"
          contents:
            - r/fixed-effects-and-clustered-standard-errors.qmd
            - r/difference-in-differences.qmd
            - r/factor-selection-via-machine-learning.qmd
            - r/option-pricing-via-machine-learning.qmd
        - section: "Portfolio Optimization"
          contents:
            - r/parametric-portfolio-policies.qmd
            - r/constrained-optimization-and-backtesting.qmd
        - section: "Appendix"
          contents: 
            - r/cover-and-logo-design.qmd
            - r/clean-enhanced-trace-with-r.qmd
            - r/proofs.qmd
            - r/hex-sticker.qmd
            - r/changelog.qmd
    - id: tidy-finance-with-python
      style: "floating"
      search: true
      collapse-level: 0
      pinned: true
      contents:
        - section: "Tidy Finance with Python"
          contents:
            - python/index.qmd
        - section: "Financial Data"
          contents:
            - python/accessing-and-managing-financial-data.qmd
  page-footer:
    center:
      - text: "&copy; Chistoph Scheuch, Stefan Voigt & Patrick Weiss"
      
editor: source
