project:
  type: website
  pre-render: pre_render_script.R

bibliography: 
  - book.bib
  - packages.bib
biblio-style: apalike
link-citations: yes
links-as-notes: true

execute: 
  freeze: auto
  eval: true
  echo: true
  warning: true
  message: false
  cache: false
  
format:
  html:
    theme: 
      light: [default, theme-light.scss]
      dark: [default, theme-dark.scss]
    css: styles.css
    toc: true
    section-divs: true
    number-sections: false
    embed-resources: false
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: false
    link-external-filter: ^(?:http:|https:)\/\/www\.tidy-finance\.org\/custom
    citations-hover: true
    footnotes-hover: true
    code-link: false
    fig-align: "center"
    fig-width: 7
    fig-height: 5
    fig-dpi: 300

website:
  title: "Tidy Finance"
  site-url: https://www.tidy-finance.org
  repo-url: https://github.com/tidy-finance/tidy-finance.org
  repo-actions: [edit, issue]
  description: "An opinionated approach on empirical research in financial economics"
  favicon: favicon.png
  open-graph: true
  page-navigation: true
  navbar:
    logo: logo-website-white.png
    pinned: false
    left:
      - href: index.qmd
        text: Book
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - icon: rss
        href: blog.xml
  sidebar:
    style: "floating"
    search: true
    collapse-level: 0
    pinned: true
    contents:
      - section: "Tidy Finance with R"
        contents:
          - index.qmd
      - section: "Getting Started"
        contents:
          - introduction-to-tidy-finance.qmd
      - section: "Financial Data"
        contents:
          - accessing-and-managing-financial-data.qmd
          - wrds-crsp-and-compustat.qmd
          - trace-and-fisd.qmd
          - other-data-providers.qmd
      - section: "Asset Pricing"
        contents: 
          - fama-macbeth-regressions.qmd
      - section: "Modeling and Machine Learning"
        contents:
          - fixed-effects-and-clustered-standard-errors.qmd
          - difference-in-differences.qmd
          - factor-selection-via-machine-learning.qmd
          - option-pricing-via-machine-learning.qmd
      - section: "Portfolio Optimization"
        contents:
          - parametric-portfolio-policies.qmd
          - constrained-optimization-and-backtesting.qmd
      - section: "Appendix"
        contents: 
          - cover-and-logo-design.qmd
          - hex-sticker.qmd
  page-footer:
    center:
      - text: "&copy; Chistoph Scheuch, Stefan Voigt & Patrick Weiss"
      
editor: source
